dbt_autochek:
  outputs:
    MART:
      account: '{{ env_var(''snowflake_account'') }}'
      database: AUTOCHECK
      password: '{{ env_var(''snowflake_pass'') }}'
      role: '{{ env_var(''snowflake_role'') }}'
      schema: MART
      threads: 2
      type: snowflake
      user: '{{ env_var(''snowflake_user'') }}'
      warehouse: '{{ env_var(''snowflake_wh'') }}'
    INTERMEDIATE:
      account: '{{ env_var(''snowflake_account'') }}'
      database: AUTOCHECK
      password: '{{ env_var(''snowflake_pass'') }}'
      role: '{{ env_var(''snowflake_role'') }}'
      schema: INTERMEDIATE
      threads: 2
      type: snowflake
      user: '{{ env_var(''snowflake_user'') }}'
      warehouse: '{{ env_var(''snowflake_wh'') }}'
    STAGING:
      account: '{{ env_var(''snowflake_account'') }}'
      database: AUTOCHECK
      password: '{{ env_var(''snowflake_pass'') }}'
      role: '{{ env_var(''snowflake_role'') }}'
      schema: STAGING
      threads: 2
      type: snowflake
      user: '{{ env_var(''snowflake_user'') }}'
      warehouse: '{{ env_var(''snowflake_wh'') }}'
    RAW:
      account: '{{ env_var(''snowflake_account'') }}'
      database: AUTOCHECK
      password: '{{ env_var(''snowflake_pass'') }}'
      role: '{{ env_var(''snowflake_role'') }}'
      schema: RAW
      threads: 2
      type: snowflake
      user: '{{ env_var(''snowflake_user'') }}'
      warehouse: '{{ env_var(''snowflake_wh'') }}'
  target: RAW
  